### ISSUE TITLE
Bad Folder Structure

### ISSUE THREAD

**Issue by KRTirtho** [tiny-css/tiny-css#6]
The folder structure of the project is messy & needs to be organized

Files like CSS, SCC, JS, HTML etc have to be in different folders. Also testing files should be in separate directory.

**Comment by FotieMConstant** [comment]
Hi, are we talking about the same folder structure here? because all I can see in the **"src"** directory are all the  various utilities
Take a look!
![image](https://user-images.githubusercontent.com/42372656/99940780-2592e080-2d6d-11eb-8fd9-ec7ea848c4b0.png)
What needs to be restructured here?

**Comment by KRTirtho** [comment]
Its simple, just have to put all the scss stuff in the in a folder named scss and sass compiled css files in css named folder in each utilities .
```
src---->
         |
         |-->css-components------------->
                                        |
                                        |-->scss (where all the scss files remains)
                                        |-->css (where al\ the compiled css modules remains)
                                        |-->html (where we keep the css design testing HTML files)
         |-->css-grid-->same as css-components
         |-->css-utility-->same as css-components
```
